#!/usr/bin/env python3
r"""The paper's tables (booktabs), fully data-driven.  Every number is read through
paper_data.py (ledger, result JSONs, wallclock benchmark, arch_stats.json), every
architecture fact from the instantiated Hydra config, every row list from
paper_manifest.yaml; the data checks behind the text's claims are assertions.

Two kinds of output:
  * a whole table float (caption, label, tabular), which main.tex inputs through
    \inputwithcaption{<file>}{<caption>}: main.tex supplies the caption it prints
     <outdir>/tab_circuit.tex            copying circuit, body models (seed means, Holm codes)
     <outdir>/tab_roster_full.tex        every 20B run: config facts, params, FLOPs, speed, NLL
     <outdir>/tab_circuit_full.tex       copying circuit, every run
     <outdir>/tab_patching.tex           activation patching recovery
     <outdir>/tab_readdepth_full.tex     read reach and read depth, every two-stream model
     <outdir>/tab_probe_floors.tex       last-layer probes, trained vs untrained
     <outdir>/tab_lesion_mean.tex        zero vs mean ablation
     <outdir>/tab_efficiency.tex         throughput, KV cache, FLOPs
  * a tabular only, whose float, caption and label are in main.tex
     <outdir>/tab_model_definitions.tex  weight sharing, read level, input, head, seeds
     <outdir>/tab_2x2.tex                weight sharing x read, plus single-read rows
     <outdir>/tab_token_gain.tex         token and gain shares, repeat-distance and induction
     <outdir>/tab_control_counts.tex     distinct pattern-matched control triples
     <outdir>/tab_finalread.tex          Sequential minus Two-tower loss by repeat distance
  and <outdir>/numbers.tex, the numbers stated in the text (paper_numbers.py).

Read level (paper convention): state level l = output of state layer l (level 0 =
embeddings).  Prediction layer l reads level
    l-1  read_map "pre"  (SPS, AF-SPS: the k/v that state layer l computes from its input)
    l    read_map "post" (Two-tower)
    l+k  read_map "top"  (Two-tower 12+6: k = L_s - L_p)
    final read_map "final" (Sequential: level L_s at every prediction layer)

Usage:  python scripts/analysis/make_tables.py [--outdir paper/tables]
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import defaultdict
from functools import lru_cache
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts" / "analysis"))

import paper_data as D  # noqa: E402  (puts src/ and scripts/ on sys.path)
from plotting import paper_style as PS  # noqa: E402
from plotting.paper_style import ARMS, MANIFEST  # noqa: E402

WC = MANIFEST["wallclock"]
BASE_TAG, FLEX_TAG = WC["reference"], WC["flex_reference"]
# the manifest's architecture vocabulary (config_facts cross-checks it)
READ_TEXT = {"post": "layer-aligned (post)", "pre": "layer-aligned (pre)",
             "final": "final layer", "top": "top-aligned"}
PRED_INPUT_TEXT = {"constant": "pause", "separate": "table"}
ALPHA = 0.05          # significance level of the circuit controls (before Holm correction)

AUTOGEN = r"% AUTO-GENERATED by scripts/analysis/make_tables.py -- do not edit by hand."
MISMATCHES: list[str] = []

# SPS's learned prediction token (Monea et al.'s <predict>; config predict_embedding:
# constant): every prediction position gets this one learned input instead of its token's
# embedding.  The tables (and the manifest labels) print it with this exact LaTeX.
PREDTOK = r"$\langle$predict$\rangle$"


def tex(s: str) -> str:
    """escape TeX specials, leaving the PREDTOK LaTeX intact"""
    return PREDTOK.join(_tex1(part) for part in s.split(PREDTOK))


def _tex1(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%")
            .replace("_", r"\_").replace("#", r"\#"))


def fmt(v, nd=3):
    """signed number; a value that rounds to zero prints as 0.000 (never -0.000)"""
    if abs(v) < 0.5 * 10 ** -nd:
        v = 0.0
    s = f"{v:.{nd}f}"
    return s.replace("-", "$-$")


# SEED RULE for every cell: one value prints plain; two print as the seed mean with half
# their range as a subscript (2.801$_{\pm.002}$).
def _pm_part(half, nd):
    """the +- part alone, e.g. '.002' (no leading 0).  A half-range that rounds to zero at
    the shown precision prints as '<.001' (a rounded zero is not zero seed variation)."""
    txt = f"{half:.{nd}f}"
    if float(txt) == 0:
        return "<." + "0" * (nd - 1) + "1" if nd > 0 else "<1"
    return txt.lstrip("0") if half < 1 else txt


def fmt_pm(vals, nd=3):
    vals = [v for v in vals if v is not None]
    if not vals:
        return "--"
    m = statistics.fmean(vals)
    if len(vals) < 2:
        return fmt(m, nd)
    half = abs(max(vals) - min(vals)) / 2
    return fmt(m, nd) + r"$_{\pm" + _pm_part(half, nd) + "}$"


def mean_only(vals, nd=3):
    """the plain seed mean (tab:circuit; the seed ranges are in tab:circuit-full)"""
    vals = [v for v in vals if v is not None]
    if not vals:
        return "--"
    return fmt(statistics.fmean(vals), nd)


def fmt_pm_v(vals, vfmt):
    """fmt_pm with a caller-supplied scalar formatter; the +- part takes the mean's decimal
    places."""
    vals = [x for x in vals if x is not None]
    if not vals:
        return "--"
    m = statistics.fmean(vals)
    if len(vals) < 2:
        return vfmt(m)
    half = abs(max(vals) - min(vals)) / 2
    txt = vfmt(m)
    nd = len(txt.rsplit(".", 1)[1]) if "." in txt else 0
    return txt + r"$_{\pm" + _pm_part(half, nd) + "}$"


def pm_caption_note(single_seed_labels) -> str:
    """The one caption sentence every table with a $\\pm$ cell states once."""
    base = r"$\pm$ is half the range over two seeds"
    if not single_seed_labels:
        return base + "."
    verb = " has" if len(single_seed_labels) == 1 else " have"
    return base + "; " + ", ".join(single_seed_labels) + verb + " one seed."


def pm_caption_note_rows(single_seed_labels) -> str:
    """pm_caption_note for a table whose model names can label both a one-seed and a
    two-seed variant: say that rows without $\\pm$ are single-seed."""
    base = r"$\pm$ is half the range over two seeds"
    return base + (r"; rows without $\pm$ have one seed." if single_seed_labels else ".")


def tabular(spec, header, body, colsep=None, fill=False):
    """A booktabs tabular (optionally after its \\tabcolsep), as a list of lines.  fill: set
    at \\linewidth as tabular* with \\extracolsep{\\fill}, so a table narrower than the text
    spreads its columns across the full width."""
    begin, end = ((r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}" + spec + "}",
                   r"\end{tabular*}") if fill else
                  (r"\begin{tabular}{" + spec + "}", r"\end{tabular}"))
    return ([r"\setlength{\tabcolsep}{" + colsep + "}"] if colsep else []) + [
        begin, r"\toprule", *header, r"\midrule", *body, r"\bottomrule", end]


def write(out: Path, stem: str, lines):
    """<out>/<stem>.tex, a tabular main.tex wraps in its own float; the last line ends in %
    so the file adds no space where it is input"""
    p = out / f"{stem}.tex"
    p.write_text("\n".join([AUTOGEN, *lines]) + "%\n")
    print(f"WROTE {p}")


def table_env(label, cap, spec, header, body, colsep, size=r"\footnotesize", pos="t"):
    """A whole table float (tabular* at \\linewidth, see `tabular`) with its own caption;
    main.tex's \\inputwithcaption replaces that caption with the one it prints."""
    return "\n".join([AUTOGEN, r"\begin{table}[" + pos + "]", r"\centering", size,
                      r"\caption{" + cap + "}", r"\label{" + label + "}",
                      *tabular(spec, header, body, colsep, fill=True), r"\end{table}", ""])


def write_float(out: Path, stem: str, text: str):
    p = out / f"{stem}.tex"
    p.write_text(text)
    print(f"WROTE {p}")


# ---------------------------------------------------------------------------------------
# architecture facts, derived from the instantiated config
# ---------------------------------------------------------------------------------------
@lru_cache(maxsize=None)
def config_facts(key: str) -> dict:
    """Shared weights / read level / LM head / prediction-stream input of an arm, read from
    its instantiated model config (paper_data.arch_stats), and cross-checked against the
    manifest's fields (disagreements are printed and collected in MISMATCHES)."""
    st = D.arch_stats(key)
    fam = st["family"]
    head = "tied" if st["tie_lm_head"] else "untied"
    if fam == "standard":
        f = dict(family=fam, tying="--", shared="--", read="--", read_disp="--", head=head,
                 pred_input="--")
    elif fam == "sps":
        # SPS: one stack serves both slots; the prediction slot at layer l reads the k/v the
        # state slots compute at layer l from their input, i.e. level l-1.
        f = dict(family=fam, tying="one stack", shared="one stack", read=READ_TEXT["pre"],
                 read_disp=r"$\ell{-}1$", head=head,
                 pred_input=PRED_INPUT_TEXT[st["predict_embedding"]])
    else:
        attn, ffn_tied = st["tie_attn_across_towers"], st["tie_ffn_across_towers"]
        ffn_pooled, norms = st["share_ffn_across_towers"], st["tie_norms_across_towers"]
        parts = [n for n, on in (("attn", attn), ("MLP", ffn_tied or ffn_pooled)) if on]
        shared = [n for n, on in (("attn.", attn), ("MLP", ffn_tied), ("pooled MLP", ffn_pooled),
                                  ("norms", norms)) if on]
        rm = st["read_map"]
        read_disp = {"pre": r"$\ell{-}1$", "post": r"$\ell$", "final": "final",
                     "top": rf"$\ell{{+}}{st['state_n_layer'] - st['pred_n_layer']}$"}[rm]
        f = dict(family=fam, tying="+".join(parts) or "none",
                 shared=", ".join(shared) or "none", read=READ_TEXT[rm], read_disp=read_disp,
                 head=head, pred_input=PRED_INPUT_TEXT[st["predict_embedding"]])
    a = ARMS[key]
    expect = {"tying": {"single stream": "--"}.get(a["tying"], a["tying"]), "read": a["read"],
              "head": a["head"], "pred_input": a["pred_input"] or "--"}
    for fld, want in expect.items():
        if want != f[fld]:
            msg = f"{key}: config gives {fld}={f[fld]!r}, the manifest says {want!r}"
            MISMATCHES.append(msg)
            print(f"[MISMATCH] {msg}")
    return f


# architecture groups of the per-model appendix tables, assigned from the config
GROUPS = ["transformer", "sps", "layer", "final", "shared"]


def arch_group(key: str) -> str:
    f = config_facts(key)
    if f["family"] == "standard":
        return "transformer"
    if f["family"] == "sps" or "pooled MLP" in f["shared"]:
        return "sps"                     # SPS and AF-SPS (one pooled MLP per position)
    if f["tying"] == "attn+MLP":
        return "shared"                  # every layer weight shared across the towers
    return "final" if f["read"] == READ_TEXT["final"] else "layer"


def paper_name(key: str) -> str:
    """The one row name every appendix table uses for an arm (manifest `name`, else its
    label)."""
    return ARMS[key].get("name") or ARMS[key]["label"]


def roster_name(key: str) -> str:
    """paper_name without its head / input qualifier, for a table whose Variant column
    states head and input on every row (tab:roster_full)"""
    n = paper_name(key).replace(", tied head", "")
    if " (" in n and ("head" in n or PREDTOK in n):
        n = n.split(" (")[0]
    return n


PRED_INPUT_SHORT = {"table": "own table", "pause": PREDTOK}


def variant(key: str, qualifiers: bool = True) -> str:
    """What distinguishes an arm from its same-name siblings, from the config: a partial
    weight share or a non-default read, then "LM head / prediction-stream input".
    qualifiers=False: head / input only."""
    f = config_facts(key)
    parts = []
    if qualifiers and f["family"] == "two_tower" and f["tying"] not in ("none", "attn+MLP") \
            and arch_group(key) != "sps":
        parts.append("shared " + f["shared"].replace(", norms", ""))
    if qualifiers and f["read"] == READ_TEXT["top"]:
        parts.append("top-aligned")
    hi = f["head"]
    if f["pred_input"] != "--":
        hi += " / " + PRED_INPUT_SHORT[f["pred_input"]]
    return "; ".join(parts + [hi])


def grouped(keys):
    """[[keys] per architecture group] in GROUPS order; within a group by size
    (non-embedding params), then name (depth split), then variant."""
    by = defaultdict(list)
    for k in keys:
        by[arch_group(k)].append(k)
    return [sorted(by[g], key=lambda k: (round(D.arch_stats(k)["params_nonemb"] / 1e6),
                                         paper_name(k), variant(k)))
            for g in GROUPS if by.get(g)]


def grouped_body(groups, row_fn):
    """booktabs body: groups separated by \\midrule (every row name says its family)."""
    body = []
    for i, items in enumerate(groups):
        if i:
            body.append(r"\midrule")
        for it in items:
            body.extend(row_fn(it))
    return body


def analysis_arms():
    """the arms of the per-model analysis tables (not the roster-only controls)"""
    return [k for k, a in ARMS.items() if not a.get("roster_only")]


# ---------------------------------------------------------------------------------------
# wall-clock
# ---------------------------------------------------------------------------------------
@lru_cache(maxsize=None)
def wallclock_by_arm():
    g = defaultdict(list)
    with open(D.WALLCLOCK) as f:
        for line in f:
            if line.strip():
                r = json.loads(line)
                if r.get("tag") == WC["tag"]:
                    g[r["arm"]].append(r)
    return g


def _num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _median_metric(rs, section):
    vals = []
    for r in rs:
        sec = r.get(section)
        if isinstance(sec, dict):
            v = _num(sec.get("tokens_per_s"))
            if v is not None:
                vals.append(v)
    return (statistics.median(vals), len(vals)) if vals else (None, 0)


def _hosts(rs, section):
    return {r.get("host") for r in rs if isinstance(r.get(section), dict)
            and _num(r[section].get("tokens_per_s")) is not None}


def head_tying_speed_effect() -> float:
    """largest relative train-throughput difference between a tied and an untied head of the
    same model and kernel (justifies one tied-head Transformer reference for both groups)"""
    W, out = wallclock_by_arm(), 0.0
    for t, u in WC["head_pairs"]:
        a, b = _median_metric(W.get(t, []), "train")[0], _median_metric(W.get(u, []), "train")[0]
        if a and b:
            out = max(out, abs(a - b) / a)
    return out


def train_rel_same_kernel() -> dict:
    """key -> train throughput relative to the same-kernel tied-head Transformer: the
    two-tower arms run on torch flex-attention (divided by the Transformer on flex), the
    Transformer and SPS on the repo's Triton kernels (divided by the Triton Transformer)."""
    W = wallclock_by_arm()
    ref = {t: _median_metric(W.get(t, []), "train")[0] for t in (BASE_TAG, FLEX_TAG)}
    exp_to_tag = {e: t for t, e in WC["arms"].items() if not t.endswith("_flex")}
    out = {}
    for key in ARMS:
        tag = exp_to_tag.get(key)
        v = _median_metric(W.get(tag, []), "train")[0] if tag else None
        rtag = FLEX_TAG if config_facts(key)["family"] == "two_tower" else BASE_TAG
        if v is not None and ref[rtag] is not None:
            out[key] = v / ref[rtag]
    return out


# ---------------------------------------------------------------------------------------
# tab:model-definitions, tab:2x2
# ---------------------------------------------------------------------------------------
WEIGHTS = {"standard": "--", "sps": "shared", "none": "separate", "attn+MLP": "shared"}
PRED_INPUT_WORDS = {"--": "--", "pause": PREDTOK + " token", "table": "own embedding"}
# SPS's read, "level l-1", glossed: prediction layer l attends to the state as it ENTERS
# state layer l
READ_GLOSS = {r"$\ell{-}1$": r"$\ell{-}1$ (input to layer $\ell$)"}


def write_model_definitions(out: Path):
    """One row per model family, grouped (main models / controls); every arm a row names
    must agree on every column."""
    body = []
    for gi, (group, rows) in enumerate(MANIFEST["model_definitions"]):
        if gi:
            body.append(r"\midrule")
        body.append(r"\multicolumn{6}{@{}l}{\emph{" + group + r"}} \\")
        for name, keys in rows:
            cells = set()
            for k in keys:
                f = config_facts(k)
                cells.add((WEIGHTS[f["family"] if f["family"] != "two_tower" else f["tying"]],
                           READ_GLOSS.get(f["read_disp"], f["read_disp"]),
                           PRED_INPUT_WORDS[f["pred_input"]], f["head"]))
            assert len(cells) == 1, (name, cells)
            seeds = {len(D.mean_runs(k)) for k in keys}
            assert len(seeds) == 1, (name, seeds)
            body.append(" & ".join([name, *cells.pop(), str(seeds.pop())]) + r" \\")
    header = [r"Model & Weights & \shortstack{State level read by\\prediction layer $\ell$} & "
              r"Prediction input & LM head & Seeds \\"]
    write(out, "tab_model_definitions", tabular("llclcc@{}", header, body, "3pt", fill=True))


def write_2x2(out: Path):
    """Validation loss by weight sharing x read (Two-tower: same-depth, Sequential: final),
    with each row's params and FLOPs: the separate-weight rows and the one-read controls,
    then the shared row and the references."""
    spec = MANIFEST["two_by_two"]

    def loss(k):
        return fmt_pm(D.nll_seeds(k), 3)

    def facts(*keys):
        """non-emb. / total params (M) and GFLOPs/token, 'a/b' when two arms differ"""
        cols = [[f"{D.arch_stats(k)['params_nonemb'] / 1e6:.1f}" for k in keys],
                [f"{D.arch_stats(k)['params_total'] / 1e6:.0f}" for k in keys],
                [f"{D.arch_stats(k)['flops_fwd_per_token'] / 1e9:.3f}" for k in keys]]
        return ["/".join(dict.fromkeys(c)) for c in cols]

    def contrast(weights, towers, tt, seq):
        ft, fs = config_facts(tt), config_facts(seq)
        # the row's placement follows from its config
        assert {ft["tying"], fs["tying"]} == ({"attn+MLP"} if weights == "Shared" else {"none"})
        assert ft["read"].startswith("layer-aligned") and fs["read"] == READ_TEXT["final"]
        d = statistics.fmean(D.nll_seeds(seq)) - statistics.fmean(D.nll_seeds(tt))
        delta = ("$+$" if d > 0 else "$-$") + f"{abs(d):.3f}"
        return " & ".join([weights, towers, loss(tt), loss(seq), delta, *facts(tt, seq)]) + r" \\"

    def one(k, cells):
        return (r"\multicolumn{2}{@{}l}{" + tex(paper_name(k)) + "} & "
                + " & ".join([*cells, "--", *facts(k)]) + r" \\")

    body = [contrast(*row) for row in spec["rows"]]
    tt_only, seq_only = spec["two_tower_only"], spec["sequential_only"]
    assert len(D.nll_seeds(tt_only)) == 1 and len(D.nll_seeds(seq_only)) == 1
    body += [one(tt_only, [loss(tt_only), "--"]), one(seq_only, ["--", loss(seq_only)])]
    # the <predict>-input variant drops the prediction table: it matches the Transformer's total
    assert facts(seq_only)[1] == facts(PS.BODY_TRANSFORMER)[1]
    body += [r"\midrule", contrast(*spec["shared"])]
    for k in spec["references"]:
        assert config_facts(k)["head"] == PS.BODY_HEAD, k
        body.append(r"\multicolumn{2}{@{}l}{" + PS.body_label(k) + r"} & \multicolumn{2}{c}{"
                    + loss(k) + "} & " + " & ".join(["--", *facts(k)]) + r" \\")
    header = [r" & & \multicolumn{2}{c}{Read} & $\Delta$ & \multicolumn{2}{c}{Params (M)} & "
              r"GFLOPs \\",
              r"\cmidrule(lr){3-4}\cmidrule(lr){6-7}",
              r"Weights & Towers & Two-tower & Sequential & Seq.$-$TT & non-emb. & total & "
              r"/token \\"]
    write(out, "tab_2x2", tabular("llcccccc@{}", header, body, "3pt", fill=True))


# ---------------------------------------------------------------------------------------
# tab:roster_full, tab:efficiency
# ---------------------------------------------------------------------------------------
def write_roster_full(out: Path):
    """One row per SEED RUN of every 20B arm; a run outside the seed-rule mean is starred."""
    L = D.ledger()
    rel = train_rel_same_kernel()
    assert head_tying_speed_effect() < 0.01
    keys = [k for k in ARMS if any(s in L for s in ARMS[k]["seeds"])]
    runs_by_key = {k: [s for s in ARMS[k]["seeds"] if s in L] for k in keys}
    mean_set = {k: set(D.mean_runs(k)) for k in keys}
    extra_notes = [tex(paper_name(k)) + ", " + ARMS[k].get("extra_note", {}).get(run, "an extra seed")
                   for k in keys for run in runs_by_key[k] if run not in mean_set[k]]
    extra = (r" $^*$: a run beyond the two the main text's seed rule means over (" +
             "; ".join(extra_notes) + ").") if extra_notes else ""
    cap = (r"Models trained on 20B tokens, one row per seed run. Variant: LM head / "
           r"prediction input; Shared: weights reused across the streams; Read: the state "
           r"level prediction layer $\ell$ reads ($\ell{-}1$: the state entering layer $\ell$). "
           r"Parameters are total and non-embedding; Speed is training throughput relative to "
           r"the tied-head Transformer on the same "
           r"attention kernel, from the benchmark of Tab.~\ref{tab:efficiency}, which prints a subset "
           r"of these models (--: not measured); NLL is "
           r"validation nats/token." + extra)
    header = [r"Model & Variant & Shared & Read & \multicolumn{2}{c}{Params (M)} & GFLOPs & "
              r"Speed & NLL \\",
              r"\cmidrule(lr){5-6}",
              r" & & & & total & non-emb. & /token & & (nats/token) \\"]

    def row(k):
        f, st, runs = config_facts(k), D.arch_stats(k), runs_by_key[k]
        n = len(runs)
        # Read shows the bare level; the caption glosses l-1 once
        arch = [tex(variant(k, qualifiers=False)), f["shared"], f["read_disp"],
                f"{st['params_total'] / 1e6:.1f}", f"{st['params_nonemb'] / 1e6:.1f}",
                f"{st['flops_fwd_per_token'] / 1e9:.3f}",
                f"{rel[k]:.2f}" if k in rel else "--"]
        lines = []
        for i, run in enumerate(runs):
            name = tex(roster_name(k)) + (f" (s{i + 1})" if n > 1 else "")
            nll = fmt(L[run], 3) + ("" if run in mean_set[k] else r"$^{*}$")
            if n > 1:
                # "=": wrap at the width of the p-columns (Variant, Shared)
                cells = [name] + ([rf"\multirow{{{n}}}{{{'=' if j < 2 else '*'}}}{{{c}}}"
                                   for j, c in enumerate(arch)] if i == 0
                                  else [""] * len(arch)) + [nll]
            else:
                cells = [name] + arch + [nll]
            lines.append(" & ".join(cells) + r" \\")
        return lines
    spec = (r">{\raggedright\arraybackslash}p{3.9cm}>{\raggedright\arraybackslash}p{2.0cm}"
            r">{\raggedright\arraybackslash}p{1.9cm}lrrrrl")
    write_float(out, "tab_roster_full", table_env(
        "tab:roster_full", cap, spec, header, grouped_body(grouped(keys), row), "2pt",
        size=r"\scriptsize"))


def write_efficiency(out: Path):
    W = wallclock_by_arm()
    rows = []
    for tag in WC["rows"]:
        rs = W.get(tag, [])
        exp = WC["arms"][tag]
        train, n = _median_metric(rs, "train")
        if train is None:
            print(f"[efficiency] no successful {WC['tag']} train rep for {tag}; skipped")
            continue
        kv = next((_num(r.get("kv_bytes_per_token")) for r in rs
                   if _num(r.get("kv_bytes_per_token")) is not None), None)
        decode = next((r["decode"].get("status") for r in rs if isinstance(r.get("decode"), dict)),
                      None)
        # same-kernel reference: the two-tower family runs on flex-attention, the rest on the
        # repo's Triton kernels (the flex Transformer row is its own reference)
        rtag = FLEX_TAG if (tag == FLEX_TAG or config_facts(exp)["family"] == "two_tower") \
            else BASE_TAG
        # head and kernel have their own columns: drop them from the row name
        # keep "tied head, " inside a qualifier: stripping it would give the tied
        # <predict>-input Sequential 6+6 the untied variant's name
        label = paper_name(exp).replace(", tied head", "").replace(" (tied head)", "")
        rows.append({"tag": tag, "exp": exp, "train": train, "n": n,
                     "prefill": _median_metric(rs, "prefill")[0], "rtag": rtag,
                     "label": label, "kv": kv, "decode": decode, "hosts": _hosts(rs, "train")})
    by = {r["tag"]: r for r in rows}
    assert head_tying_speed_effect() < 0.01
    # every Sequential 6+6 row caches exactly the Transformer's K/V
    six = [r for r in rows if config_facts(r["exp"])["family"] == "two_tower"
           and D.arch_stats(r["exp"])["state_n_layer"] == 6]
    assert six and all(r["kv"] == by[BASE_TAG]["kv"] for r in six), six
    flex_other_node = by[FLEX_TAG]["hosts"] != by[BASE_TAG]["hosts"]
    cap = (r"Throughput (thousand tokens/s) on one H100 (bf16, \texttt{torch.compile}, "
           r"micro-batch $12\times4096$, median of "
           + "/".join(map(str, sorted({r["n"] for r in rows})))
           + r" repetitions), bf16 key/value cache per token, and forward FLOPs per token. "
           r"Speed is training throughput relative to the tied-head Transformer on the same "
           r"attention kernel (Kernel column): Triton for the Transformer and SPS, "
           r"flex-attention for the two-tower models and AF-SPS" +
           ("; the flex-kernel Transformer reference ran on another node"
            if flex_other_node else "")
           + r". Compare speeds within a kernel.")
    body = []
    for r in rows:
        lab = tex(r["label"])
        if r["decode"] == "no_decode_path":
            lab += r"$^{a}$"
        if r["prefill"] is None:
            lab += r"$^{b}$"
        body.append(" & ".join([
            lab, config_facts(r["exp"])["head"], "flex" if r["rtag"] == FLEX_TAG else "Triton",
            f"{r['train'] / 1e3:.0f}", f"{r['train'] / by[r['rtag']]['train']:.2f}",
            "--" if r["prefill"] is None else f"{r['prefill'] / 1e3:.0f}",
            "--" if r["kv"] is None else f"{r['kv'] / 1024:.0f}",
            f"{D.arch_stats(r['exp'])['flops_fwd_per_token'] / 1e9:.3f}"]) + r" \\")
    notes = [n for n, on in ((r"$^{a}$No incremental decode implementation.",
                              any(r["decode"] == "no_decode_path" for r in rows)),
                             (r"$^{b}$No successful prefill measurement in this benchmark run.",
                              any(r["prefill"] is None for r in rows))) if on]
    header = [r" & & & \multicolumn{2}{c}{Train} & Prefill & K/V & GFLOPs \\",
              r"\cmidrule(lr){4-5}",
              r"Model & Head & Kernel & ktok/s & Speed & ktok/s & KiB/token & /token \\"]
    txt = table_env("tab:efficiency", cap, "lllrrrrr", header, body, "3pt")
    if notes:
        txt = txt.replace(r"\end{tabular*}" + "\n" + r"\end{table}",
                          "\n".join([r"\end{tabular*}", r"\par\smallskip",
                                     r"\begin{minipage}{\linewidth}\footnotesize",
                                     r"\quad ".join(notes), r"\end{minipage}", r"\end{table}"]))
    write_float(out, "tab_efficiency", txt)


# ---------------------------------------------------------------------------------------
# circuit tables
# ---------------------------------------------------------------------------------------
CTRL_FILES = [("random_any", "ctrl-random_any-n100"),
              ("pattern_matched", "ctrl-pattern_matched-n100-k5"),
              ("random_any_exL1", "ctrl-random_any-n100-exL1"),
              ("pattern_matched_exL1", "ctrl-pattern_matched-n100-k5-exL1")]
CTRL_MODE = {m: m.replace("_exL1", "") for m, _ in CTRL_FILES}
P_PAIRS = [("random_any", "pattern_matched"), ("random_any_exL1", "pattern_matched_exL1")]
P_METRIC = "induction_clean_top1"   # ctrl_summary.headline: accuracy lost on these tokens
HOLM_POOLS = ("random_any", "pattern_matched")


def prev_mass(a5, q, k=None):
    """max over heads of query stream q (optionally only key population k) of the
    natural-text previous-token attention mass."""
    rows = [r for r in a5["natural"]["per_head"] if r["query_stream"] == q
            and (k is None or r["key_stream"] == k) and "prev_token_mass" in r]
    return max(max(r["prev_token_mass"]) for r in rows)


def check_prev_mass(a5):
    for q in a5["query_streams"]:
        prof = max(v["max_prev_token_mass"] for v in a5["prev_token_profile"].values()
                   if v["stream"] == q)
        assert abs(prof - round(prev_mass(a5, q), 5)) < 1e-5, (a5["run"], q, prof)


def _has_l1(draw):
    return any(h["block"] == 0 for h in draw["heads"])    # layer 1 = block 0


@lru_cache(maxsize=None)
def ctrl_files(run) -> dict:
    """{mode: a9 control JSON} for the 100-draw control files of `run` that exist"""
    out = {}
    for mode, suffix in CTRL_FILES:
        d = D.result("a9_patching", f"{run}_{suffix}")
        if d is not None:
            out[mode] = d
    return out


def ctrl_p(run):
    """{mode: dict(k, n, p, k_l1, drivers, draws)} from the 100-draw control files, every
    mode on ONE metric: accuracy lost on induction tokens the clean model predicts correctly.
    p+1 is recomputed from the draws and asserted equal to the stored one; k_l1 = exceeding
    draws that contain a layer-1 head; drivers = heads (layer, head), both 1-indexed, present
    in every exceeding draw."""
    out = {}
    for mode, d in ctrl_files(run).items():
        assert d["ctrl_mode"] == CTRL_MODE[mode], (run, d["ctrl_mode"], mode)
        excl = d.get("ctrl_exclude_layers") or []
        assert (excl == [1]) == mode.endswith("exL1"), (run, mode, excl)
        h = d["ctrl_summary"]["headline"]
        assert h["metric"] == "accuracy lost on " + P_METRIC, (run, h["metric"])
        draws = [x for x in d["ctrl_draws"] if x["sets"].get(P_METRIC, {}).get("n")]
        if excl:
            assert not any(_has_l1(x) for x in draws), (run, mode)
        costs = [-x["sets"][P_METRIC]["d_acc_control"] for x in draws]
        prev = float(h["prev_cost"])
        for src in (d, D.result("a9_patching", run)):
            assert abs(prev + src["natural"][P_METRIC]["d_acc"]) < 1e-9, run
        assert len(costs) == h["n_draws"] == d["n_ctrl_draws"] == 100, run
        ge = [c >= prev - 1e-9 for c in costs]
        k = sum(ge)
        ex = [x for g, x in zip(ge, draws) if g]
        drivers = set.intersection(*[{(hd["block"] + 1, hd["head"] + 1) for hd in x["heads"]}
                                     for x in ex]) if ex else set()
        p = (k + 1) / (len(costs) + 1)
        assert abs(p - h["p_plus1"]) < 1e-9, (run, mode, p, h["p_plus1"])
        out[mode] = dict(k=k, n=len(costs), p=p, drivers=drivers,
                         k_l1=sum(g and _has_l1(x) for g, x in zip(ge, draws)),
                         draws=[frozenset((hd["block"], hd["head"]) for hd in x["heads"])
                                for x in draws])
    return out


def circuit_rows(entries):
    """entries: [(key, label, runs)] -> one row per run with an a5 JSON: previous-token
    mass / mean lift / heads with lift > 3 per query stream (split by key population where
    a model has two), the a9 induction-token ablation vs. its same-layer control, and the
    100-draw p+1 values where the control files exist."""
    rows = []
    for key, label, runs in entries:
        seeds = D.result_seeds("a5_induction", key, runs=runs)
        if not seeds:
            print(f"[circuit] no a5 for {key}; skipped")
            continue
        for run, a5 in seeds:
            check_prev_mass(a5)
            nat = (D.result("a9_patching", run) or {}).get("natural", {})
            ind, allt = nat.get("induction"), nat.get("all")
            abl = None if not ind else (ind["d_nll"], ind.get("d_nll_control"))
            allc = None if not allt else (allt["d_nll"], allt.get("d_nll_control"))
            agg = a5["natural"]["aggregate_2x2"]
            qs = list(a5["query_streams"])            # ["single"] or ["state", "pred"]
            key_pops = a5["key_streams"]
            sub = []
            for kp in key_pops:
                cs = [agg[f"{q}_query__{kp}_key"] for q in qs]
                nhs = [c["n_heads"] for c in cs]   # per query stream (asym 12+6: 144 / 72)
                nh = nhs[0] if len(set(nhs)) == 1 else "/".join(map(str, nhs))
                pm = [prev_mass(a5, q, kp if len(key_pops) > 1 else None) for q in qs]
                pad = [None] * (2 - len(qs))           # single stream: no P column
                sub.append(dict(kp=kp, pm=pm + pad, lift=[c["mean_lift"] for c in cs] + pad,
                                gt3=[c["n_heads_lift_gt3"] for c in cs] + pad, nh=nh))
            rows.append(dict(key=key, run=run, label=label,
                             seed=ARMS[key]["seeds"].index(run) + 1,
                             nseeds=len(seeds), sub=sub, abl=abl, allc=allc, ps=ctrl_p(run)))
    return rows


def _pair(a, b, nd=3):
    return "/".join("--" if v is None else fmt(v, nd) for v in (a, b))


def _kp_name(name, kp, first):
    kp = {"state": "state keys", "pred": "pred.\\ keys"}[kp]
    return f"{name}, {kp}" if first else r"\quad " + kp


def _multirow_tail(cells, tail, i, n):
    """SPS rows split by key population share their tail cells (\\multirow)."""
    if n > 1:
        return cells + ([rf"\multirow{{{n}}}{{*}}{{{c}}}" for c in tail] if i == 0
                        else [""] * len(tail))
    return cells + tail


def circuit_body(rows):
    """tab:circuit-full: one row per run (and key population)."""
    body = []
    prev_key = None
    for r in rows:
        if prev_key is not None and r["key"] != prev_key:
            body.append(r"\addlinespace")
        prev_key = r["key"]
        abl = "--" if r["abl"] is None else _pair(*r["abl"])
        allc = "--" if r["allc"] is None else _pair(*r["allc"])
        ps = ["/".join(f"{r['ps'][m]['p']:.3f}" if m in r["ps"] else "--" for m in pair)
              if any(m in r["ps"] for m in pair) else "--" for pair in P_PAIRS]
        name = tex(r["label"]) + (f" (s{r['seed']})" if r["nseeds"] > 1 else "")
        for i, s in enumerate(r["sub"]):
            heads = "/".join("--" if v is None else str(v) for v in s["gt3"])
            cells = [_kp_name(name, s["kp"], i == 0) if len(r["sub"]) > 1 else name,
                     _pair(*s["pm"], nd=2), _pair(*s["lift"], nd=2), heads]
            body.append(" & ".join(_multirow_tail(cells, [abl, allc] + ps, i, len(r["sub"])))
                        + r" \\")
    return body


def _holm_sig(ps, alpha=ALPHA):
    """Holm-Bonferroni step-down over one seed's family of tests (ps: {mode: {p, ...}}).
    Returns {mode: bool}: whether that test's p survives, comparing the i-th smallest p to
    alpha/(n-i)."""
    items = sorted(ps.items(), key=lambda kv: kv[1]["p"])
    sig, chain_ok = {}, True
    for i, (mode, v) in enumerate(items):
        chain_ok = chain_ok and v["p"] <= alpha / (len(items) - i)
        sig[mode] = chain_ok
    return sig


def holm_code(run, pool):
    """One seed's Holm verdict for one control pool (Holm within the (model, seed) family
    of its 4 controls): 'all' if the ablation is Holm-significant against that pool both
    with control heads from all layers and with layer 1 excluded; 'excl.' if only with
    layer 1 excluded; '--' if neither.  (Significant over all layers but not after
    excluding layer 1 does not occur; asserted.)"""
    sig = {m for m, ok in _holm_sig(run["ps"]).items() if ok}
    a, e = pool in sig, pool + "_exL1" in sig
    assert not (a and not e), (run["run"], pool, run["ps"])
    return "all" if a else ("excl." if e else "--")


def holm_cells(runs):
    """(random cell, pattern-matched cell), each 'seed1/seed2' of holm_code."""
    return tuple("/".join(holm_code(r, pool) for r in runs) for pool in HOLM_POOLS)


def circuit_body_by_model(rows):
    """tab:circuit: one row per model (SPS split into its state-keys / pred.-keys sub-rows),
    seed means for prev.-mass, lift and the two DeltaNLL columns, and the Holm codes."""
    groups = {}
    for r in rows:
        groups.setdefault(r["key"], []).append(r)
    body = []
    for gi, runs in enumerate(groups.values()):
        n_sub = len(runs[0]["sub"])
        if gi and n_sub > 1:      # set the two key-population sub-rows apart
            body.append(r"\addlinespace")
        hr, hp = holm_cells(runs)

        def col(field, j, i=None):
            return mean_only([(r["sub"][i][field][j] if i is not None else
                               (r[field][j] if r[field] else None)) for r in runs],
                             2 if i is not None else 3)
        for i in range(n_sub):
            name = tex(runs[0]["label"])
            if n_sub > 1:
                name = _kp_name(name, runs[0]["sub"][i]["kp"], i == 0)
            cells = [name, f"{col('pm', 0, i)}/{col('pm', 1, i)}",
                     f"{col('lift', 0, i)}/{col('lift', 1, i)}"]
            tail = [f"{col('abl', 0)}/{col('abl', 1)}", f"{col('allc', 0)}/{col('allc', 1)}",
                    hr if i == 0 else "", hp if i == 0 else ""]
            body.append(" & ".join(_multirow_tail(cells, tail, i, n_sub)) + r" \\")
    return body


def _ctrl_files_complete(run):
    """True iff the four 100-draw a9 control files of `run` exist and parse with 100 draws;
    a seed whose control files are still being written is left out of tab:circuit."""
    try:
        return set(ctrl_p(run)) == {m for m, _ in CTRL_FILES}
    except (AssertionError, KeyError, ValueError):   # json.JSONDecodeError is a ValueError
        return False


def circuit_runs(k):
    """seed rule for tab:circuit: runs with an a5 JSON, its a9 companion and all four
    complete a9 control files"""
    return D.pick_seeds(k, lambda r: D.result("a5_induction", r) is not None
                        and D.result("a9_patching", r) is not None
                        and _ctrl_files_complete(r))


CIRCUIT_BODY_CAP = (
    r"The copying circuit on natural text, one row per model (SPS split by attended key "
    r"population; Transformer and SPS are reference models). Per stream (S/P = "
    r"state/prediction), seed means: peak previous-token attention and mean "
    r"induction lift (heads with lift $>3$ as a fraction of heads per stream, 144 at "
    r"12+12 / 72 at 6+6, are in Tab.~\ref{tab:circuit-full}); $\Delta$NLL (nats/token) "
    r"zeroing the state "
    r"stream's top-3 previous-token heads vs.\ three low-mass control heads, on induction "
    r"tokens and on all tokens. \emph{Holm-specific}: for seed 1\,/\,seed 2 and each control "
    r"pool (random, pattern-matched), whether the ablation is Holm-significant ($\alpha{=}"
    + f"{ALPHA:g}" + r"$, four tests per seed: 2 pools $\times$ \{with, without layer 1\}): "
    r"all, with control heads from all layers and with layer 1 excluded; excl., only with "
    r"layer 1 excluded; --, neither. Layers and heads are "
    r"numbered from 1. SPS's state-keys and pred.-keys sub-rows share one set of "
    r"$\Delta$NLL and Holm values (shown once via \texttt{multirow}), since the head "
    r"ablation and its accuracy test are the same for both key populations."
    r" Seed means are shown; full seed ranges are in Tab.~\ref{tab:circuit-full} "
    r"(appendix).")


def write_circuit(out: Path):
    tt12, sq12, tt6, sq6 = D.INTER, D.SEQ, D.INTER6, D.SEQ6
    entries = [(k, PS.body_label(k), circuit_runs(k)) for k in MANIFEST["circuit"]["rows"]]
    for key, label, runs in entries:
        print(f"[tab_circuit] {label} ({key}): seeds used = {runs or 'NONE'}")
    rows = circuit_rows(entries)

    # ---- data checks behind the text's claims ----------------------------------------------
    for r in rows:   # the fixed same-layer control is cheaper on every run
        assert r["abl"] and r["abl"][0] > r["abl"][1], r["run"]
        assert r["allc"] is not None, ("all-token delta missing", r["run"])
        if r["key"] not in (PS.BODY_SPS, PS.BODY_TRANSFORMER):
            s0 = r["sub"][0]
            assert s0["pm"][0] > s0["pm"][1] and s0["lift"][1] > s0["lift"][0], r["run"]

    def sig(r, pair):
        return all(r["ps"][m]["p"] <= ALPHA for m in pair)
    r12 = [r for r in rows if r["key"] in (tt12, sq12)]
    assert len(r12) == 4 and all(set(r["ps"]) == {m for m, _ in CTRL_FILES}
                                 and sig(r, r["ps"]) for r in r12), [r["run"] for r in r12]
    sus = [r for r in rows if r["key"] == PS.BODY_SPS]
    assert sus and all(not sig(su, P_PAIRS[0]) and sig(su, P_PAIRS[1]) for su in sus)
    exc = []
    for r in [r for r in rows if r["key"] in (tt6, sq6)]:
        pm = r["ps"]["pattern_matched"]
        # all-layer pattern-matched control fails, and only through layer-1 draws ...
        assert pm["p"] > ALPHA and pm["k_l1"] == pm["k"] > 0, (r["run"], pm)
        # ... and with layer 1 excluded from the pool the controls pass, bar exceptions
        exc += [(r, m) for m in P_PAIRS[1] if r["ps"][m]["p"] > ALPHA]
    # the exceptions are random (not pattern-matched) draws on second seeds only
    assert 1 <= len(exc) <= 2 and all(m == "random_any_exL1" and r["run"].endswith("_seed2")
                                       for r, m in exc), [(r["run"], m) for r, m in exc]
    for e_run, e_mode in exc:
        print(f"[tab_circuit] exL1 exception {e_run['run']} {e_mode}: "
              f"p={e_run['ps'][e_mode]['p']:.3f} drivers={e_run['ps'][e_mode]['drivers']}")
    nh = {s["nh"] for r in rows for s in r["sub"]}
    assert nh == {144, 72} and {s["nh"] for r in rows if r["key"] in (tt6, sq6)
                                for s in r["sub"]} == {72}, nh
    # the Holm-corrected per-seed, per-pool codes are the ones the text reports
    got = {}
    for r in rows:
        got.setdefault(r["key"], []).append(r)
    got = {k: list(holm_cells(rs)) for k, rs in got.items()}
    assert got == MANIFEST["circuit"]["verdicts"], got
    # "only Sequential 12+12 passes all four tests in both seeds"
    assert [k for k, v in got.items() if v == ["all/all", "all/all"]] == [sq12]

    header = [r"Model & Prev.\ mass & Mean lift & \multicolumn{2}{c}{$\Delta$NLL, abl./ctrl.} & "
              r"\multicolumn{2}{c}{Holm-specific, s1/s2} \\",
              r"\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
              r" & S/P & S/P & induct.\ tok. & all tok. & random & pattern \\"]
    write_float(out, "tab_circuit", table_env(
        "tab:circuit", CIRCUIT_BODY_CAP, "lcccccc", header, circuit_body_by_model(rows), "3pt",
        pos="!htbp"))
    return rows


CIRCUIT_FULL_CAP = (
    r"The copying circuit for every trained model and seed with the analysis (body: "
    r"Tab.~\ref{tab:circuit}). The Transformer has one stream (S column); SPS rows "
    r"are split by which slot's keys (state / prediction) are attended. "
    r"Per query stream (S = state, P = prediction): the largest previous-token attention of "
    r"any head, the mean matching lift over heads, and heads with lift $>3$ (of "
    r"12 $\times$ the stream's layers: 144 at 12 layers, 72 at 6); $\Delta$NLL "
    r"(nats/token) on induction tokens when the state stream's top-3 previous-token heads "
    r"/ three low-mass heads of the same layers are zeroed, and the same ablation's cost "
    r"over ALL tokens (not just induction tokens). $p{=}(k{+}1)/101$ compares the "
    r"top-1 accuracy the ablation removes on induction tokens the intact model gets right "
    r"with 100 random / pattern-matched three-head draws, from all layers (specified before "
    r"the result) "
    r"or post hoc, excluding layer 1 (--: not run). Layers and heads are "
    r"numbered from 1.")


def write_circuit_full(out: Path):
    """Every run (every seed) of the manifest's circuit_full models."""
    entries = [(k, paper_name(k), list(ARMS[k]["seeds"])) for k in MANIFEST["circuit_full"]]
    rows = circuit_rows(entries)
    # prediction queries have the higher mean lift in every separated model that forms a
    # matching circuit (AF-SPS, mean lift ~1.1 on both streams, forms none)
    for r in rows:
        s0 = r["sub"][0]
        if config_facts(r["key"])["family"] == "two_tower" and max(s0["lift"]) > 1.5:
            assert s0["lift"][1] > s0["lift"][0], r["run"]
        if r["key"] == D.AFSPS:
            assert max(s0["lift"]) < 1.5 and s0["gt3"] == [0, 0], r["run"]
    tr = [r for r in rows if r["run"] == D.TRANSFORMER]
    assert tr and all(r["ps"][m]["p"] <= ALPHA for m, _ in CTRL_FILES for r in tr), tr
    header = [r"Model & Prev.\ mass & Mean lift & Lift $>3$ & "
              r"\multicolumn{2}{c}{$\Delta$NLL, abl./ctrl.} & \multicolumn{2}{c}{$p$, rand./match.} \\",
              r"\cmidrule(lr){5-6}\cmidrule(lr){7-8}",
              r" & S/P & S/P & S/P & induct.\ tok. & all tok. & all layers & excl.\ L1 \\"]
    write_float(out, "tab_circuit_full", table_env(
        "tab:circuit-full", CIRCUIT_FULL_CAP, r">{\raggedright\arraybackslash}p{3.9cm}ccccccc",
        header, circuit_body(rows), "1.8pt", size=r"\scriptsize", pos="htbp"))
    return rows


def write_control_counts(out: Path):
    """Per model and seed: the number of distinct three-head sets among the 100
    pattern-matched control draws, with control heads from all layers / layer 1 excluded."""
    body = []
    for k in MANIFEST["control_counts"]:
        cells = []
        for run in circuit_runs(k):
            n = {m: len(set(v["draws"])) for m, v in ctrl_p(run).items()}
            # "all 100 random draws are distinct in each pool"
            assert n["random_any"] == n["random_any_exL1"] == 100, (run, n)
            cells.append(f"{n['pattern_matched']}/{n['pattern_matched_exL1']}")
        assert len(cells) == 2, (k, cells)
        body.append(" & ".join([PS.body_label(k), *cells]) + r" \\")
    header = [r"Model & Seed 1 & Seed 2 \\"]
    write(out, "tab_control_counts", tabular("lcc", header, body, fill=True))


# ---------------------------------------------------------------------------------------
# appendix per-model tables
# ---------------------------------------------------------------------------------------
def _body_name(k):
    return paper_name(k) if k == D.SPS else PS.body_label(k)


def write_lesion_mean(out: Path):
    """Zero vs mean ablation of whole layers (a12 block lesions), per body model:
    Spearman rho of the two per-layer profiles and the layer-1 cost under each."""
    models = D.result("a12_depth_lesion", "zero_vs_mean")["models"]
    body, rho, single_seed = [], [], []
    for k in PS.body_arms():
        runs = D.pick_seeds(k, models)          # seed rule
        if not runs:
            print(f"[lesion_mean] no zero-vs-mean profiles for {k}; skipped")
            continue
        if len(runs) < 2:
            single_seed.append(tex(_body_name(k)))
        prof = {st: [models[r]["profiles"][f"{st}_block"] for r in runs] for st in ("state", "pred")}
        rho += [p["spearman"] for v in prof.values() for p in v]
        body.append(" & ".join(
            [tex(_body_name(k)),
             fmt_pm([p["spearman"] for p in prof["state"]], 2),
             fmt_pm([p["spearman"] for p in prof["pred"]], 2),
             *[fmt_pm([p[ab][0] for p in prof[st]], 2)
               for st in ("state", "pred") for ab in ("zero", "mean")]]) + r" \\")
    assert min(rho) > 0.5, rho     # the zero- and mean-ablation profiles agree in rank
    header = [r" & \multicolumn{2}{c}{Spearman $\rho$} & \multicolumn{2}{c}{Layer 1, state}"
              r" & \multicolumn{2}{c}{Layer 1, prediction} \\",
              r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
              r"Model & state & pred. & zero & mean & zero & mean \\"]
    cap = (r"Whole-layer lesions under zero ablation (the layer's output replaced by 0) "
           r"and mean ablation (replaced by its per-channel mean "
           r"on clean text), for the body models with both (the Transformer has no "
           r"stream split). Spearman $\rho$ compares the two per-layer profiles of each stream; "
           r"the layer-1 columns give the loss increase (nats/token) of lesioning state or "
           r"prediction layer 1 under each ablation. " + pm_caption_note(single_seed))
    write_float(out, "tab_lesion_mean", table_env(
        "tab:lesion_mean", cap, "lrrrrrr", header, body, "4pt", pos="htbp"))


def _probe_last(d, tower, tg):
    recs = [r for r in d["probes"].values() if r.get("tower") == tower
            and isinstance(r.get("block"), int) and r["block"] >= 0]
    return float(max(recs, key=lambda r: r["block"])[tg]["eval_nll"])


def probe_floor_rows():
    """{body arm: {target: (trained last-layer probe per seed, untrained per init file)}} and
    the mean bigram floors {target: nats}"""
    rows, bigram = {}, defaultdict(list)
    for k in PS.body_arms():
        tr = [d for _, d in D.result_seeds("a20_role_probe", k)]
        init = [json.loads(p.read_text()) for run in D.init_runs(k) for p in D.init_files(run)]
        if not tr or not init:
            print(f"[probe_floors] {k}: trained {len(tr)}, init {len(init)}; skipped")
            continue
        single = any(r.get("tower") == "single" for r in tr[0]["probes"].values())
        tw = {"P1": "single" if single else "pred", "P3": "single" if single else "state"}
        rows[k] = {tg: ([_probe_last(d, tw[tg], tg) for d in tr],
                        [_probe_last(d, tw[tg], tg) for d in init]) for tg in ("P1", "P3")}
        for d in init:
            fl = d.get("floors") or {}
            for tg, f in D.BIGRAM_FLOOR.items():
                if f in fl:
                    bigram[tg].append(float(fl[f]))
    return rows, {tg: statistics.fmean(v) for tg, v in bigram.items()}


def write_probe_floors(out: Path):
    """Last-layer role probes, trained vs untrained init, per body model."""
    rows, bg = probe_floor_rows()
    for k, c in rows.items():     # trained below both untrained and bigram, per stream
        for tg in ("P1", "P3"):
            t, u = c[tg]
            assert max(t) < min(u) and max(t) < bg[tg], (k, tg, t, u)
    body = [" & ".join([tex(_body_name(k)), fmt_pm(c["P1"][0], 2), fmt_pm(c["P1"][1], 2),
                        fmt_pm(c["P3"][0], 2), fmt_pm(c["P3"][1], 2)]) + r" \\"
            for k, c in rows.items()]
    single_seed = [tex(_body_name(k)) for k, c in rows.items() if len(c["P1"][0]) < 2]
    header = [r" & \multicolumn{2}{c}{Next token (prediction)} & "
              r"\multicolumn{2}{c}{Previous token (state)} \\",
              r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
              r"Model & trained & untrained & trained & untrained \\"]
    cap = (r"Linear-probe loss (nats; lower = more readable) at the last layer for the next "
           r"token in the prediction stream and the previous token in the state stream (the "
           r"Transformer's single stream for both), trained and at "
           r"untrained initialization. A probe that knows only the current token (bigram "
           r"lookup) reaches " + f"{bg['P1']:.2f}" + r" (next) and " + f"{bg['P3']:.2f}"
           + r" (previous). " + pm_caption_note(single_seed)
           + r" Untrained entries without $\pm$ use one initialization.")
    write_float(out, "tab_probe_floors", table_env(
        "tab:probe_floors", cap, "lllll", header, body, "4pt", pos="htbp"))


PATCH_ARMS = (("prev1_answer_slot", "head"), ("ctrl_donor_prev1_answer_slot", "donor"))


def patching_recs() -> dict:
    """{arm: [{'head' | 'donor': (recovery fraction, 95% CI)} per seed]}: the answer-slot
    interchange patch of the state stream's strongest previous-token head, or a random donor"""
    recs = {}
    for k in analysis_arms():
        seeds = []
        for run, d in D.result_seeds("a9_patching", k):
            try:
                a = d["patching"]["natural"]["arms"]
                seeds.append({t: (float(a[arm]["recovery_fraction"]),
                                  [float(v) for v in a[arm]["recovery_ci95"]])
                              for arm, t in PATCH_ARMS})
            except (KeyError, TypeError):
                print(f"[patching] {run}: no answer-slot arms; skipped")
        if seeds:
            recs[k] = seeds
    return recs


def write_patching(out: Path):
    recs = patching_recs()

    def cell(k, t):
        # two seeds: seed 1 / seed 2 (each rounded once, matching the prose); one seed: the
        # value with its within-run 95% bootstrap interval in brackets
        vs = [s[t][0] for s in recs[k]]
        if len(vs) == 1:
            lo, hi = recs[k][0][t][1]
            return fmt(vs[0], 2) + r" {\scriptsize[" + fmt(lo, 2) + ", " + fmt(hi, 2) + "]}"
        return " / ".join(fmt(v, 2) for v in vs)

    def row(k):
        return [" & ".join([tex(paper_name(k)), cell(k, "head"), cell(k, "donor")]) + r" \\"]
    single_seed = [k for k in recs if len(recs[k]) < 2]
    cap = (r"Activation patching on validation text with a duplicated 256-token segment: "
           r"recovery from patching the strongest previous-token head at the answer slot, or "
           r"a random donor (control). Recovery is "
           r"$(\overline D_{\rm patched}-\overline D_{\rm corrupted})/(\overline D_{\rm clean}"
           r"-\overline D_{\rm corrupted})$, where $D$ is the answer-versus-distractor logit "
           r"difference. Two-seed rows give seed 1 / seed 2; one-seed rows give the value with "
           r"its within-run 95\% bootstrap interval in brackets.")
    write_float(out, "tab_patching", table_env(
        "tab:patching", cap, "lll", [r"Model & Head patched in & Random donor \\"],
        grouped_body(grouped(list(recs)), row), "4pt", pos="htbp"))


def _a13_grid(k, which):
    """{K: [delta per seed]} on the D.KS grid, dropping the native map and K beyond depth."""
    out = defaultdict(list)
    for _, d in D.a13_seeds(k):
        for K, y in zip(*D.a13_curve(d, which)):
            if K in D.KS:
                out[K].append(y)
    return out


def write_readdepth_full(out: Path):
    """Per-model read reach (a2: keep the N most recent state positions, far keys masked or
    mean-replaced) and read depth (a13: levels <= k / >= k)."""
    keys = [k for k in analysis_arms() if arch_group(k) != "transformer"]
    a2 = {k: {ab: D.a2_means(k, ab) for ab in ("mask", "mean")} for k in keys}
    a13 = {k: {w: _a13_grid(k, w) for w in ("caps", "floors")} for k in keys}
    # a13 sweeps whose read source was never trained as a read (a13_valid); captioned
    bad = [k for k in keys
           if any(not D.a13_valid(r, d) for r, d in D.result_seeds("a13_read_depth_cap", k))]
    keys = [k for k in keys if a2[k]["mask"] or a13[k]["caps"]]
    # a13 applies min/max(l, k) to the SAME-DEPTH (Two-tower) map l; for a model whose native
    # read is not same-depth (Sequential, 12+6) every bound also moves it off its native read
    starred = {k for k in keys if config_facts(k)["read"] != READ_TEXT["post"]}

    def v(x):
        return "--" if x is None else (f"{x:.3f}" if abs(x) < 0.1 else f"{x:.2f}")

    single_seed = set()

    def row_a(k):
        if 0 < max(len(a2[k]["mask"]), len(a2[k]["mean"])) < 2:
            single_seed.add(tex(paper_name(k)))
        cells = [fmt_pm_v([c[i] for c in a2[k][ab]], v) if a2[k][ab] else "--"
                 for ab in ("mask", "mean") for i in range(len(D.A2_CAPS))]
        return [" & ".join([tex(paper_name(k))] + cells) + r" \\"]

    def row_b(k, w):
        g = a13[k]
        if 0 < max([len(x) for w_ in g.values() for x in w_.values()] or [0]) < 2:
            single_seed.add(tex(paper_name(k)))
        cells = [fmt_pm_v(g[w][K], v) if g[w].get(K) else "--" for K in D.KS]
        if all(c == "--" for c in cells):    # no bound inside this model's state depth
            return []
        name = tex(paper_name(k)) + (r"$^{\ast}$" if k in starred else "")
        return [" & ".join([name] + cells) + r" \\"]

    ns = " & ".join(map(str, D.A2_CAPS))
    hdr_a = [r" & \multicolumn{4}{c}{masked, $N{=}$} & "
             r"\multicolumn{4}{c}{mean-replaced, $N{=}$} \\",
             r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
             r"Model & " + ns + " & " + ns + r" \\"]

    def hdr_b(w):
        rel = r"\leq" if w == "caps" else r"\geq"
        return [r" & \multicolumn{6}{c}{levels $" + rel + r" k$, $k{=}$} \\",
                r"\cmidrule(lr){2-7}",
                r"Model & " + " & ".join(map(str, D.KS)) + r" \\"]
    spec_a, spec_b = "l" + "r" * 8, "l" + "r" * 6
    # the reach table's natural width is measured in box 0: too wide -> scaled down to
    # \linewidth; otherwise re-set as tabular* at \linewidth.  The read-depth grid is two
    # 6-column tables (levels <= k, levels >= k) that fit at \scriptsize.
    body_a = tabular(spec_a, hdr_a, grouped_body(grouped([k for k in keys if a2[k]["mask"]]),
                                                 row_a))[1:-1]
    tab_a = [r"\sbox0{%", r"\begin{tabular}{" + spec_a + "}", *body_a, r"\end{tabular}}%",
             r"\ifdim\wd0>\linewidth\resizebox{\linewidth}{!}{\usebox0}\else",
             r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}" + spec_a + "}", *body_a,
             r"\end{tabular*}\fi"]
    tab_b = []
    for w in ("caps", "floors"):
        tab_b += [r"\par\medskip"] + tabular(
            spec_b, hdr_b(w), grouped_body(grouped([k for k in keys if a13[k]["caps"]]),
                                           lambda k, w=w: row_b(k, w)), fill=True)
    cap = (r"Loss increase (nats/token; models as in "
           r"Tab.~\ref{tab:roster_full}) for every two-stream model "
           r"when prediction may read (top) only the $N$ most recent state positions, the "
           r"farther keys masked out or replaced by their mean, and (middle, bottom) only state "
           r"levels no deeper ($\leq K$) or no shallower ($\geq K$) than $K$, each prediction "
           r"layer's read level $\ell$ moved to $\min(\ell, K)$ or $\max(\ell, K)$ (--: $K$ "
           r"beyond the state depth, or the unchanged native read). $^{\ast}$Native read not "
           r"same-depth (Sequential: level $L_s$ from every layer; 12+6: level $\ell{+}6$): the "
           r"bounds are applied to the same-depth map $\ell$, so every bound, even $K{=}12$, "
           r"also moves every layer off its native read. The read-depth test does not "
           r"apply to SPS and AF-SPS (they read the keys each state layer computes)"
           + (r"; " + ", ".join(tex(paper_name(k)) for k in bad)
              + r" reuses the state tower's own keys and values, so its "
              r"bounds substitute untrained reads and are not shown" if bad else "") + ". "
           + pm_caption_note_rows(sorted(single_seed)))
    write_float(out, "tab_readdepth_full", "\n".join([
        AUTOGEN, r"\begin{table}[htbp]", r"\centering", r"\scriptsize",
        r"\caption{" + cap + "}", r"\label{tab:readdepth_full}", r"\setlength{\tabcolsep}{2pt}",
        *tab_a, *tab_b, r"\end{table}", ""]))


# ---------------------------------------------------------------------------------------
# where Sequential's gain falls: tab:finalread (repeat distance), tab:token-gain
# ---------------------------------------------------------------------------------------
BUCKETS = [("never", "never"), ("1-16", "1--16 back"), ("17-64", "17--64"),
           ("65-256", "65--256"), ("257-1024", "257--1024"), ("1025+", "$>$1024")]


def read_contrasts():
    """{'12+12' | '6+6': (Two-tower arm, Sequential arm)}: the separate-weight rows of tab:2x2"""
    return {towers: (tt, seq) for w, towers, tt, seq in MANIFEST["two_by_two"]["rows"]}


def repeat_distance():
    """g3_final_read_mechanism's A3 buckets per depth, checked against the seed rule"""
    g3 = json.loads((D.RESULTS / "g3_final_read_mechanism.json").read_text())
    out = {}
    for towers, (tt, seq) in read_contrasts().items():
        assert config_facts(tt)["tying"] == config_facts(seq)["tying"] == "none"
        a3 = g3["pairs"][towers]["a3"]
        assert a3["runs"]["tt"] == D.mean_runs(tt) and a3["runs"]["seq"] == D.mean_runs(seq)
        out[towers] = a3
    return out


def induction_sweep():
    """{towers: [(induction-token share, share of Sequential's gain) per same-seed pair]} on
    a9's natural-text sweep: gain share = (n_ind / n_all) (Delta_ind / Delta_all), Delta =
    Two-tower minus Sequential mean NLL."""
    out = {}
    for towers, (tt, seq) in read_contrasts().items():
        out[towers] = []
        for rt, rs in zip(D.mean_runs(tt), D.mean_runs(seq)):
            a, b = D.result("a9_patching", rt)["natural"], D.result("a9_patching", rs)["natural"]
            assert a["all"]["n"] == b["all"]["n"] and a["induction"]["n"] == b["induction"]["n"]
            share = a["induction"]["n"] / a["all"]["n"]
            gain = ((a["induction"]["clean_nll"] - b["induction"]["clean_nll"])
                    / (a["all"]["clean_nll"] - b["all"]["clean_nll"]))
            out[towers].append((share, share * gain))
    return out


def pct_range(vals, nd=0):
    lo, hi = (f"{100 * v:.{nd}f}" for v in (min(vals), max(vals)))
    return lo if lo == hi else f"{lo}--{hi}"


def write_finalread(out: Path):
    rd = repeat_distance()
    order = ("12+12", "6+6")
    shares = {rd[t]["buckets"][b]["share"] for t in order for b, _ in BUCKETS}
    assert len(shares) == len(BUCKETS)          # both depths score the same tokens
    body = []
    for b, name in BUCKETS:
        cells = [name, f"{100 * rd[order[0]]['buckets'][b]['share']:.1f}\\%"]
        for t in order:
            x = rd[t]["buckets"][b]
            cells += [f"${x['diff_seq_minus_tt']:.3f}$", f"${x['rel_diff_pct']:.1f}$\\%",
                      f"{100 * x['share_of_gain']:.0f}\\%"]
        body.append(" & ".join(cells) + r" \\")
    body += [r"\midrule", "all & 100\\% & " + " & & & ".join(
        f"${rd[t]['overall_diff_seq_minus_tt']:.3f}$" for t in order) + r" & & \\"]
    header = [r" & & \multicolumn{3}{c}{12+12} & \multicolumn{3}{c}{6+6} \\",
              r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}",
              r"Last occurrence & tokens & $\Delta$ & rel. & gain & $\Delta$ & rel. & gain \\"]
    write(out, "tab_finalread", tabular("lrrrrrrr", header, body, "4pt", fill=True))


def write_token_gain(out: Path):
    rd, ind = repeat_distance(), induction_sweep()
    never = [rd[t]["buckets"]["never"] for t in rd]
    ind_share = {round(s, 12) for pairs in ind.values() for s, _ in pairs}
    assert len({x["share"] for x in never}) == 1 and len(ind_share) == 1
    body = [f"Never-seen (R) & {100 * never[0]['share']:.1f}\\% & "
            f"{pct_range([x['share_of_gain'] for x in never])}\\% \\\\",
            f"Induction tokens (I) & {100 * ind_share.pop():.1f}\\% & "
            f"{pct_range([g for pairs in ind.values() for _, g in pairs])}\\% \\\\"]
    header = [r"Token group & Share of tokens & Share of Sequential's gain \\"]
    write(out, "tab_token_gain", tabular("lcc@{}", header, body, "6pt", fill=True))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--outdir", default=str(REPO / "paper" / "tables"))
    a = ap.parse_args()
    out = Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)
    for w in (write_model_definitions, write_2x2, write_circuit, write_token_gain,
              write_roster_full, write_circuit_full, write_control_counts, write_patching,
              write_readdepth_full, write_probe_floors, write_lesion_mean, write_finalread,
              write_efficiency):
        w(out)
    import paper_numbers
    paper_numbers.write(out)
    if MISMATCHES:
        print(f"[MISMATCH] {len(MISMATCHES)} config/manifest disagreement(s):")
        for m in MISMATCHES:
            print("   ", m)
    else:
        print("config facts agree with the manifest for every arm checked")


if __name__ == "__main__":
    main()
